package ast;

import environment.Environment;

/**
 * An Assignment object consists of a variable and the expression that
 * the variable needs to be assigned to. This object can execute itself
 * by inputting the variable and corresponding value in the environment.
 * 
 * @author Sadhika Malladi
 * @date   101014
 *
 */
public class Assignment extends Statement 
{
	private String var;
	private Expression exp;
	
	/**
	 * Below is a basic constructor to initialize the instance variables
	 * of this Assignment.
	 * 
	 * @param variable   the variable to be assigned
	 * @param expression the expression to be assigned to the variable
	 */
	public Assignment(String variable, Expression expression)
	{
		var=variable;
		exp=expression;
	}
	
	/**
	 * The exec method executes the assignment by adding the variable 
	 * and its corresponding value to the environment passed (or a child
	 * environment if appropriate). The value is generated by evaluating 
	 * the expression associated with this Assignment.
	 * 
	 * @param env the environment to add the variable to
	 */
	public void exec(Environment env)
	{
		env.setVariable(var, exp.eval(env));
	}
}
